### ISSUE TITLE
throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by coozgan** [fawwaz37/whatsapp-gateway#9]
Hi I am having trouble running after doing `npm start
`
Can someone help me? I am running using Node.js v18.15.0
```
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED ::1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
Emitted 'error' event on Query instance at:
    at /Users/<user>/Documents/Development/Node/whatsapp-gateway/node_modules/mysql2/lib/pool.js:144:20
    at /Users/<user>/Documents/Development/Node/whatsapp-gateway/node_modules/mysql2/lib/pool.js:60:18
    at PoolConnection.<anonymous> (/Users/<user>/Documents/Development/Node/whatsapp-gateway/node_modules/mysql2/lib/connection.js:775:13)
    at Object.onceWrapper (node:events:628:26)
    at PoolConnection.emit (node:events:525:35)
    at PoolConnection._notifyError (/Users/<user>/Documents/Development/Node/whatsapp-gateway/node_modules/mysql2/lib/connection.js:236:12)
    at PoolConnection._handleFatalError (/Users/<user>/Documents/Development/Node/whatsapp-gateway/node_modules/mysql2/lib/connection.js:167:10)
    at PoolConnection._handleNetworkError (/Users/<user>/Documents/Development/Node/whatsapp-gateway/node_modules/mysql2/lib/connection.js:180:10)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 3306,
  fatal: true
}
```

**Comment by fawwaz37** [comment]
Before running the program, make sure that your SQL server is running
